#
# Copyright (C) 2023-2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: pr-check

on: [pull_request]

jobs:
  build:
    name: Build / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-2022"
          - os: "macos-14"
          - os: "ubuntu-22.04"
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Execute pnpm
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm typecheck

        # skip formatter on windows
      - name: Run formatter
        if: ${{ matrix.os=='ubuntu-22.04' || matrix.os=='macos-14' }}
        run: pnpm format:check

      - name: Run linter
        run: pnpm lint:check

      - name: Run tests
        run: pnpm test

      - name: Run build
        run: pnpm build
        timeout-minutes: 40

  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-24.04
    env:
      SKIP_INSTALLATION: true
    steps:
    
      - uses: actions/checkout@v4
        if: github.event_name == 'schedule'
        with: 
          path: extension-minikube

      - uses: actions/checkout@v4
        with:
          repository: podman-desktop/podman-desktop
          ref: main
          path: podman-desktop

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          package_json_file: ./podman-desktop/package.json

      - name: Revert unprivileged user namespace restrictions in Ubuntu 24.04
        run: |
          # allow unprivileged user namespace
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build OpenShift Local extension from container file
        working-directory: ./extension-minikube
        run: |
          podman build -t minikube_image . -f ./Containerile
          CONTAINER_ID_MINIKUBE=$(podman create localhost/minikube_image --entrypoint "")
          podman export $CONTAINER_ID_MINIKUBE > /tmp/minikube_extension.tar
          mkdir -p tests/playwright/output/minikube-e2e-tests/plugins
          tar -xf /tmp/minikube_extension.tar -C tests/playwright/output/minikube-e2e-tests/plugins
          mv tests/playwright/output/minikube-e2e-tests/plugins/extension tests/playwright/output/minikube-e2e-tests/plugins/minikubeextension
         
      - name: Install Minikube CLI
        id: minikube
        uses: medyagh/setup-minikube@latest
        with: 
          start: false

      - name: Ensure Minikube CLI is installed
        run: |
          minikube version
            
      - name: Execute pnpm
        working-directory: ./podman-desktop
        run: pnpm install

      - name: Build Podman Desktop for E2E tests
        working-directory: ./podman-desktop
        run: pnpm build

      - name: Ensure getting current HEAD version of the test framework
        working-directory: ./extension-minikube
        run: |
          # workaround for https://github.com/containers/podman-desktop-extension-bootc/issues/712
          version=$(npm view @podman-desktop/tests-playwright@next version)
          echo "Version of @podman-desktop/tests-playwright to be used: $version"
          jq --arg version "$version" '.devDependencies."@podman-desktop/tests-playwright" = $version' package.json > package.json_tmp && mv package.json_tmp package.json
          pnpm install --lockfile-only
      - name: Execute pnpm in Minikube Extension
        working-directory: ./extension-minikube
        run: pnpm install

      - name: Run All E2E tests
        working-directory: ./extension-minikube
        env:
          PODMAN_DESKTOP_ARGS: ${{ github.workspace }}/podman-desktop
        run: pnpm test:e2e
