name: e2e-main-tmate

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      organization:
        default: 'podman-desktop'
        description: 'Organization of the extension-minikube repository'
        type: string
        required: true
      repositoryName:
        default: 'extension-minikube'
        description: 'Podman Desktop Minikube extension repository name'
        type: string
        required: true
      branch:
        default: 'main'
        description: 'Podman Desktop Minikube extension repo branch'
        type: string
        required: true
      minikube_driver: 
        description: 'Minikube cluster driver'
        type: choice
        options:
        - docker
        - podman 
        required: true

jobs:
  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Clone Minikube extension repository workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        with:
          repository: ${{ github.event.inputs.organization }}/${{ github.event.inputs.repositoryName }}
          ref: ${{ github.event.inputs.branch }}
          path: ${{ github.event.inputs.repositoryName }}

      - uses: actions/checkout@v4
        with: 
          path: extension-minikube

      - uses: actions/checkout@v4
        with:
          repository: podman-desktop/podman-desktop
          ref: main
          path: podman-desktop

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          package_json_file: ./podman-desktop/package.json

      - name: Set the default minikube cluster driver env. variable
        env:
          DEFAULT_MINIKUBE_DRIVER: 'docker'
        run: |
          echo "MINIKUBE_DRIVER=${{ github.event.inputs.minikube_driver || env.DEFAULT_MINIKUBE_DRIVER }}" >> $GITHUB_ENV

      - name: Revert unprivileged user namespace restrictions in Ubuntu 24.04
        run: |
          # allow unprivileged user namespace
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install Minikube CLI
        id: minikube
        uses: medyagh/setup-minikube@latest
        with: 
          start: false

      - name: Ensure Minikube CLI is installed
        run: |
          minikube version
            
      - name: Execute pnpm
        working-directory: ./podman-desktop
        run: pnpm install

      - name: Build Podman Desktop for E2E tests
        working-directory: ./podman-desktop
        run: pnpm build
      
      - name: Ensure getting current HEAD version of the test framework
        working-directory: ./extension-minikube
        run: |
          # workaround for https://github.com/containers/podman-desktop-extension-bootc/issues/712
          version=$(npm view @podman-desktop/tests-playwright@next version)
          echo "Version of @podman-desktop/tests-playwright to be used: $version"
          jq --arg version "$version" '.devDependencies."@podman-desktop/tests-playwright" = $version' package.json > package.json_tmp && mv package.json_tmp package.json

      - name: Execute pnpm in Minikube Extension
        working-directory: ./extension-minikube
        run: pnpm install --no-frozen-lockfile